name: Capitalico
favicon: null
layout_spectrum: 0.6313005606643856
typography_spectrum: 0.5807691535446793
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.49067289335653186
  lightness: 0.021737741539254785
  saturation: 0.18199104792438447
  rhythmicContrast: 0.25932520790956914
purpose: []
